# Generated by Django 4.2.15 on 2025-02-07 23:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('idCarrusel', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenCarrusel', models.ImageField(upload_to='imagenes/', verbose_name='Imagen/es de carrusel')),
                ('tituloCarrusel', models.CharField(max_length=200, verbose_name='tituloCarrusel')),
                ('descripcionCarrusel', models.CharField(max_length=1500, verbose_name='Motivo de Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePais', models.CharField(max_length=50, unique=True, verbose_name='Nombre de País')),
                ('iconoPais', models.ImageField(upload_to='imagenes/', verbose_name='Icono de País')),
                ('tipoMoneda', models.CharField(choices=[('eu', 'EURO'), ('uf', 'UF')], max_length=2, verbose_name='UF o EURO')),
                ('codigoCelular', models.CharField(max_length=4, verbose_name='Código de País')),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('idPropiedad', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloPropiedad', models.CharField(max_length=100, verbose_name='Titulo de Propiedad')),
                ('direccionPropiedad', models.CharField(max_length=100, verbose_name='Dirección de Propiedad')),
                ('descripcionPropiedad', models.CharField(max_length=1500, verbose_name='Descripción de Propiedad')),
                ('caracteristicasPropiedad', models.CharField(max_length=1500, null=True, verbose_name='Características de Propiedad')),
                ('precioPropiedad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Precio de Propiedad')),
                ('tipoPropiedad', models.CharField(choices=[('ar', 'Arriendo'), ('ve', 'Venta')], max_length=2, verbose_name='Arriendo o Venta')),
                ('disponibilidadPropiedad', models.CharField(choices=[('si', 'Disponible'), ('no', 'No Disponible')], max_length=2, verbose_name='Disponibilidad')),
                ('habitacionesPropiedad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Cantidad de Habitaciones')),
                ('bannosPropiedad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Cantidad de Baños')),
                ('metroscubPropiedad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Metros Cuadrados de Propiedad')),
                ('jardinPropiedad', models.CharField(choices=[('si', 'Si tiene Jardín'), ('no', 'No tiene Jardín')], max_length=2, verbose_name='¿Tiene Jardín?')),
                ('patioPropiedad', models.CharField(choices=[('si', 'Si tiene Patio'), ('no', 'No tiene Patio')], max_length=2, verbose_name='¿Tiene Patio?')),
                ('garagePropiedad', models.CharField(choices=[('si', 'Si tiene Garage'), ('no', 'No tiene Garage')], max_length=2, verbose_name='¿Tiene Garage?')),
                ('sotanoPropiedad', models.CharField(choices=[('si', 'Si tiene Sótano'), ('no', 'No tiene Sótano')], max_length=2, verbose_name='¿Tiene Sótano?')),
                ('ofertaPropiedad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% de Oferta')),
                ('paisPropiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bien_estar_app.pais', verbose_name='País de Propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenPropiedad', models.ImageField(upload_to='imagenes/', verbose_name='Imagen/es de Propiedad')),
                ('idPropiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bien_estar_app.propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenesPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen1Propiedad', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Portada')),
                ('imagen2Propiedad', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen de Propiedad')),
                ('imagen3Propiedad', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen de Propiedad')),
                ('imagen4Propiedad', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen de Propiedad')),
                ('imagen5Propiedad', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen de Propiedad')),
                ('imagen6Propiedad', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen de Propiedad')),
                ('imagen7Propiedad', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen de Propiedad')),
                ('imagen8Propiedad', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen de Propiedad')),
                ('imagen9Propiedad', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen de Propiedad')),
                ('imagen10Propiedad', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen de Propiedad')),
                ('imagen11Propiedad', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen de Propiedad')),
                ('imagen12Propiedad', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen de Propiedad')),
                ('imagen13Propiedad', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen de Propiedad')),
                ('imagen14Propiedad', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen de Propiedad')),
                ('imagen15Propiedad', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen de Propiedad')),
                ('idPropiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='bien_estar_app.propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('idContacto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Contacto')),
                ('nombresContacto', models.CharField(max_length=200, verbose_name='Nombres de Contacto')),
                ('apellidosContacto', models.CharField(max_length=200, verbose_name='Apellidos de Contacto')),
                ('emailContacto', models.CharField(max_length=200, verbose_name='Correo de Contacto')),
                ('celularContacto', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Celular')),
                ('motivoContacto', models.CharField(max_length=1500, verbose_name='Motivo de Contacto')),
                ('fechaContacto', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Contacto')),
                ('leido', models.CharField(choices=[('no', 'No Leído'), ('si', 'Leído')], default='no', max_length=2, null=True, verbose_name='Leído / No Leído')),
                ('tipoContacto', models.CharField(choices=[('comp', 'Compra'), ('coar', 'Compra Arriendo'), ('vear', 'Venta Arriendo'), ('vent', 'Venta'), ('otro', 'Otro')], max_length=4, verbose_name='Venta / Busca Arrendatarios / Otro')),
                ('codigoPaisCelular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bien_estar_app.pais', verbose_name='Código País')),
                ('idPropiedadContacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bien_estar_app.propiedad', verbose_name='ID de Propiedad por Contacto')),
            ],
        ),
    ]
