# Generated by Django 4.2.15 on 2026-04-08 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bien_estar_app', '0002_alter_pais_tipomoneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='tipoMoneda',
            field=models.CharField(choices=[('eu', 'EURO'), ('uf', 'UF')], max_length=2, verbose_name='UF o EURO'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
