# Generated by Django 4.2.15 on 2026-04-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien_estar_app', '0003_alter_pais_tipomoneda_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='tipoMoneda',
            field=models.CharField(choices=[('uf', 'UF'), ('eu', 'EURO')], max_length=2, verbose_name='UF o EURO'),
        ),
    ]
